Edwin
catclops/IT115-3185-A4-G1 pull request #4
Opened 2020-10-30 09:51 UTC by krayzieeddi

It's still not finished but I just wanted you guys to see the progress so far. Also still waiting on the others to add their candidate to the google doc. Any comments or changes you guys want to do to the format I got going so far?

2020-10-30 16:19 UTC, WChihWen requested changes
The 42nd line lost "<"

2020-10-30 16:19 UTC, WChihWen commented on index.html
> +			p>Michael Gerard Tyson was born on June 30, 1966 in Brooklyn, New York to a young Jimmy Kirkpatrick and Lorna Tyson.
There is a < p > tag, but it lost "<".

2020-10-30 19:10 UTC, catclops reviewed
Agreed with Chih. I looked over the code and all I could see was the missing "<" for line 42.

2020-10-31 00:16 UTC, Squirrel10 approved these changes
I like the look of the page!

2020-10-31 07:05 UTC, krayzieeddi commented on index.html
> +			p>Michael Gerard Tyson was born on June 30, 1966 in Brooklyn, New York to a young Jimmy Kirkpatrick and Lorna Tyson.
ok i added in the last < to it.

2020-11-01 01:25 UTC, WChihWen approved these changes
It's good to update. I'll merge it.

2020-11-01 01:25 UTC, merged